// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/ahmadammarm/inventory-backend/internal/user/handler"
	"github.com/ahmadammarm/inventory-backend/internal/user/repos"
	"github.com/ahmadammarm/inventory-backend/internal/user/service"
	"github.com/go-playground/validator/v10"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializedUser(db *gorm.DB, val *validator.Validate) *handler.UserHandler {
	userRepos := repos.NewUserRepository(db)
	userService := service.NewUserService(userRepos)
	userHandler := handler.NewUserHandler(userService, val)
	return userHandler
}
